version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo Installing dependencies...

  build:
    commands:
      - echo Build started
      - echo Building Docker image...
      - docker build -t my-app .
      # 선택: ECR 푸시
      # - $(aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin <ECR_URI>)
      # - docker tag my-app:latest <ECR_URI>/my-app:latest
      # - docker push <ECR_URI>/my-app:latest
artifacts:
  files:
    - '**/*'
